### ISSUE TITLE
Create BaseSampler

### ISSUE THREAD

**Issue by Deathn0t** [deephyper/metalgpy#1]
Have `BaseSampler` located at `mpy.sampler.BaseSampler`

- [x] Create `BaseSampler` class which takes `expression, distributions, random_state` as input parameters
- [x] collect the default distributions for each variable from the `_dist` attribute
- [x] Implement the `sample(self, size=None)` which returns a numpy array of samples if the size is None then it should return a 1-d array, if the size is integer then it should return a (size, num_variables) array
- [x] Move the `_sample` function inside `VarExpression`(s) to BaseSampler

```python
exp = mpy.meta(obj)(
  x=mpy.Int(0, 10, “x”),
  a=mpy.Float(0, 10, “a”),
  b=mpy.Float(0, 10, “b”)
)
config = {“x”: 1}
exp.freeze(config)
distributions = [
 ([“x”], univariate_distribution), 
 ([“a”, “b”], multivariate_distribution)
]
sampler = mpy.BaseSampler(exp, distributions)
array = sampler.sample(size)
# if size = None, it return only 1 dict directly
# if size >= 1, it returns a list of dict (like scipy.stats rvs function
```

**Comment by akhilpandey95** [comment]
ec68e753857e413659b5104b955031592f62811c
